In [2]:
import numpy as np
a =np.array([1000])
print(a)
print(type(a))

[1000]
<class 'numpy.ndarray'>


In [4]:
## 1-D array
a =np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
## 2-D aray
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [7]:
## 3-D array
a =np.array([[
    [1,2,3], [4,5,6]
]])
print(a)
print(type(a))

[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


In [3]:
## 4-D array
a = np.array([[[
    [1,2,3],[4,5,6], [7,8,9],[10,11,12]
]]])
print(a)
print(type(a))

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
<class 'numpy.ndarray'>
