## creating 1_D array


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## Creating 2-D array

In [4]:
import numpy as np
arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


## Creating 3-D array

In [9]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]]])
print(arr)
## checking the type 
print(type(arr))
## chceking the dimention
print(arr.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
<class 'numpy.ndarray'>
3


In [12]:
## creating 5-D 
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print('numbers of dimentions: ', arr.ndim)

[[[[[1 2 3 4 5]]]]]
numbers of dimentions:  5
